name: test
on: [push, pull_request]
jobs:
  test:
    name: "Test on Node.js ${{ matrix.node_version }}"
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: [ 14, 16, 18 ]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install
        run: yarn install
      - name: Test
        run: yarn test
